broccolijs/broccoli-concat

.gitattributes, appveyor.yml, package.json, test/test.js
This PR cleans up the unit tests in several ways described in the commit messages.
/cc @stefanpenner @ef4
=> Test Cleanup

README.md
=> Add missing comma in readme

package.json
This commit whitelists the 3 production files to avoid including unneeded files in the npm package.
[fixes #72]
Before:
```
PATH                                           SIZE      %
test/expected/.gitkeep                         0 B       0%
.npmignore                                     0 B       0%
test/.npmignore                                0 B       0%
test/expected/nothing.css                      0 B       0%
.gitattributes                                 14 B      0%
test/fixtures/second/sneaky.js/thing.js        24 B      0%
.travis.yml                                    30 B      0%
test/expected/nothing.js                       32 B      0%
test/fixtures/first/other/third.js             48 B      0%
test/expected/sneaky.js                        55 B      0% …
```
=> Whitelist production files

package.json
=> chore(package): update fast-sourcemap-concat to version 1.0.1

package.json
Whitelisting files in 2.3-stable branch per @stefanpenner's [comment](https://github.com/ember-cli/broccoli-concat/pull/73#issuecomment-237457772)
=> Whitelist production files for 2.x branch

concat-without-source-maps.js, concat.js, package.json, test/concat-without-maps-test.js, test/test.js
backport of https://github.com/ember-cli/broccoli-concat/pull/76 to 2.3.x
=> Concat stats 2.3 stable

concat.js, test/test.js
ConcatWithMaps, is confusingly named. As it can be with or without maps depend ending on the strategy
=> improve plugin name

README.md, concat.js, package.json, test/concat-without-maps-test.js, test/test.js
this enables, * postProcessing to discover other attributes:
* gzip size
* uglify size
* etc...
=> when CONCAT_STATS is enabled, provide actual input files

package.json, test/test.js
=> Assert that sourcemaps are actually valid

.travis.yml, appveyor.yml, package.json, yarn.lock
by pinning `fast-sourcemap-concat` to v1.1.x and including #116 
Addresses https://github.com/broccolijs/broccoli-concat/pull/116#issuecomment-349067711
/cc @stefanpenner @rwjblue @ef4
=> Fix CI builds

.travis.yml, appveyor.yml, package.json
This should unblock #115 
/cc @stefanpenner @rwjblue
=> CI: Replace Node 0.12 with Node 8 and 9

.eslintrc, concat-without-source-maps.js, concat.js, lib/strategies/simple.js
=> Convert to ES6 classes

package.json, test/concat-without-maps-test.js, test/simple-concat-test.js, test/sourcemap-concat-test.js
=> Use `co` to simplify test code

concat.js, lib/strategies/simple.js, test/simple-concat-test.js, test/strategies/simple-test.js
This reverts commit ec6877c834fdc67266fede8e81836959d736eab3.
=> Revert "[PATCH]Read synchronously for larger files while concatenating"

concat.js, test/simple-concat-test.js, test/sourcemap-concat-test.js
We need to create the stats directory lazily as well.
Fixes #136
=> Fix creation of empty stats directory

package.json, yarn.lock
- Please see issue #141 -- not sure this is strictly needed but might be nice to resolve anyway.
=> Upgrade: lodash.merge to prevent potential vulnerability (fix #141)

lib/strategies/simple.js, test/simple-concat-test.js
=> Support allowNone + CONCAT_STATS

.eslintrc, package.json, test/helpers/expect-file.js, test/simple-concat-test.js, test/sourcemap-concat-test.js, yarn.lock
1. broccoli
2. broccoli-plugin
3. broccoli-source
4. broccoli-merge-tree
5. mocha
=> Upgrading all the versions

concat.js, package.json, yarn.lock
Depends and adapt the changes from https://github.com/broccolijs/broccoli-plugin/pull/41/
=> Use FSFacade provided by broccoli-plugin

concat.js, yarn.lock
=> changing writeFileSync to  outputFileSync

test/simple-concat-test.js, test/sourcemap-concat-test.js
=> Add test for case outputFile having subpath
